-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 11:01:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sportproducts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportproducts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportproducts` DEFAULT CHARACTER SET utf8 ;
USE `sportproducts` ;

-- -----------------------------------------------------
-- Table `sportproducts`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `Brand_id` INT NOT NULL,
  `Type_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Brand1_idx` (`Brand_id` ASC) VISIBLE,
  INDEX `fk_Product_Type1_idx` (`Type_id` ASC) VISIBLE,
  INDEX `fk_Product_Category1_idx` (`Category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_id`)
    REFERENCES `sportproducts`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Type1`
    FOREIGN KEY (`Type_id`)
    REFERENCES `sportproducts`.`Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `sportproducts`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `sportproducts`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportproducts`.`Order_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportproducts`.`Order_Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Order_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `count` INT NOT NULL,
  INDEX `fk_Order_has_Product_Product1_idx` (`Product_id` ASC) VISIBLE,
  INDEX `fk_Order_has_Product_Order1_idx` (`Order_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Order_has_Product_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `sportproducts`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `sportproducts`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
